/**
 * constants/mockData.js
 * Data dummy katalog makanan untuk FlavorDash
 * Menggunakan gambar dari Unsplash (public CDN) agar bisa dipakai tanpa aset lokal
 */

export const CATEGORIES = [
  { id: 'all', label: 'Semua', icon: '🍽️' },
  { id: 'main', label: 'Makanan Utama', icon: '🍛' },
  { id: 'snack', label: 'Camilan', icon: '🍟' },
  { id: 'drink', label: 'Minuman', icon: '🥤' },
  { id: 'dessert', label: 'Dessert', icon: '🍰' },
  { id: 'healthy', label: 'Sehat', icon: '🥗' },
];

export const FOOD_ITEMS = [
  {
    id: '1',
    name: 'Nasi Goreng Spesial',
    description: 'Nasi goreng dengan telur, ayam, sayur segar, dan bumbu rempah pilihan',
    price: 25000,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80',
    rating: 4.8,
    reviewCount: 234,
    prepTime: '15 menit',
    calories: 520,
    badge: 'popular',
    tags: ['pedas', 'nasi', 'ayam'],
    isFavorite: false,
  },
  {
    id: '2',
    name: 'Mie Ayam Bakso',
    description: 'Mie kenyal dengan ayam cincang, bakso sapi, dan kuah kaldu gurih',
    price: 22000,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&q=80',
    rating: 4.6,
    reviewCount: 187,
    prepTime: '12 menit',
    calories: 480,
    badge: 'new',
    tags: ['mie', 'bakso', 'ayam'],
    isFavorite: true,
  },
  {
    id: '3',
    name: 'Ayam Geprek Sambal',
    description: 'Ayam crispy geprek dengan sambal bawang pedas nampol dan lalapan segar',
    price: 28000,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400&q=80',
    rating: 4.9,
    reviewCount: 312,
    prepTime: '18 menit',
    calories: 650,
    badge: 'popular',
    tags: ['pedas', 'ayam', 'crispy'],
    isFavorite: false,
  },
  {
    id: '4',
    name: 'Gado-Gado Jakarta',
    description: 'Sayuran segar rebus dengan saus kacang kental, kerupuk, dan lontong',
    price: 18000,
    category: 'healthy',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
    rating: 4.5,
    reviewCount: 98,
    prepTime: '10 menit',
    calories: 320,
    badge: 'healthy',
    tags: ['vegetarian', 'kacang', 'sayur'],
    isFavorite: false,
  },
  {
    id: '5',
    name: 'Pisang Goreng Crispy',
    description: 'Pisang kepok goreng crispy dengan taburan gula halus dan keju parut',
    price: 12000,
    category: 'snack',
    image: 'https://images.unsplash.com/photo-1587132137056-bfbf0166836e?w=400&q=80',
    rating: 4.4,
    reviewCount: 156,
    prepTime: '8 menit',
    calories: 280,
    badge: null,
    tags: ['manis', 'goreng', 'pisang'],
    isFavorite: true,
  },
  {
    id: '6',
    name: 'Es Teh Manis Jumbo',
    description: 'Teh manis segar dengan es batu, pilihan teh pilihan premium',
    price: 8000,
    category: 'drink',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80',
    rating: 4.7,
    reviewCount: 421,
    prepTime: '3 menit',
    calories: 120,
    badge: 'popular',
    tags: ['dingin', 'manis', 'teh'],
    isFavorite: false,
  },
  {
    id: '7',
    name: 'Es Alpukat Krim',
    description: 'Alpukat segar blender dengan susu kental manis, es batu, dan sirup cokelat',
    price: 18000,
    category: 'drink',
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400&q=80',
    rating: 4.8,
    reviewCount: 178,
    prepTime: '5 menit',
    calories: 310,
    badge: 'new',
    tags: ['alpukat', 'dingin', 'susu'],
    isFavorite: false,
  },
  {
    id: '8',
    name: 'Martabak Manis Spesial',
    description: 'Martabak tebal lembut dengan isian cokelat, keju, dan kacang tanah',
    price: 35000,
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=400&q=80',
    rating: 4.9,
    reviewCount: 267,
    prepTime: '20 menit',
    calories: 720,
    badge: 'popular',
    tags: ['manis', 'cokelat', 'keju'],
    isFavorite: true,
  },
  {
    id: '9',
    name: 'Soto Ayam Lamongan',
    description: 'Soto ayam bening khas Lamongan dengan soun, telur, koya, dan sambal',
    price: 20000,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80',
    rating: 4.7,
    reviewCount: 143,
    prepTime: '10 menit',
    calories: 380,
    badge: null,
    tags: ['soto', 'ayam', 'kuah'],
    isFavorite: false,
  },
  {
    id: '10',
    name: 'Salad Bowl Sehat',
    description: 'Campuran sayuran segar, quinoa, alpukat, tomat ceri dengan dressing lemon',
    price: 32000,
    category: 'healthy',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
    rating: 4.6,
    reviewCount: 89,
    prepTime: '7 menit',
    calories: 290,
    badge: 'healthy',
    tags: ['vegetarian', 'sehat', 'segar'],
    isFavorite: false,
  },
  {
    id: '11',
    name: 'Cireng Bumbu Rujak',
    description: 'Cireng gurih renyah dengan cocolan bumbu rujak pedas asam segar',
    price: 10000,
    category: 'snack',
    image: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=400&q=80',
    rating: 4.3,
    reviewCount: 112,
    prepTime: '8 menit',
    calories: 240,
    badge: null,
    tags: ['cireng', 'pedas', 'goreng'],
    isFavorite: false,
  },
  {
    id: '12',
    name: 'Es Krim Gelato Matcha',
    description: 'Gelato premium rasa matcha Jepang dengan taburan red bean dan mochi',
    price: 28000,
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1567206563114-c179706a56b4?w=400&q=80',
    rating: 4.8,
    reviewCount: 198,
    prepTime: '2 menit',
    calories: 350,
    badge: 'new',
    tags: ['matcha', 'es krim', 'manis'],
    isFavorite: true,
  },
];

// Mock user credentials untuk login
export const MOCK_USERS = [
  {
    id: 'usr_001',
    email: 'user@flavordash.com',
    password: 'password123',
    name: 'User',
    avatar: 'https://i.pravatar.cc/150?img=8',
    phone: '0812-3456-7890',
    address: 'Jl. Kebon Sirih No.12, Jakarta Pusat',
    memberSince: '2023-05-10',
  },
  {
    id: 'usr_002',
    email: 'admin@flavordash.com',
    password: 'admin123',
    name: 'Admin FlavorDash',
    avatar: 'https://i.pravatar.cc/150?img=12',
    phone: '0811-0000-0001',
    address: 'Kantor Pusat FlavorDash, Jakarta',
    memberSince: '2022-01-01',
  },
];

// Data pesanan dummy untuk halaman detail pesanan (protected route)
export const MOCK_ORDERS = [
  {
    id: 'ORD-20240701-001',
    date: '2024-07-01',
    status: 'delivered',
    statusLabel: 'Terkirim',
    items: [
      { foodId: '1', name: 'Nasi Goreng Spesial', qty: 2, price: 25000 },
      { foodId: '6', name: 'Es Teh Manis Jumbo',  qty: 2, price: 8000  },
    ],
    deliveryFee: 5000,
    address: 'Jl. Kebon Sirih No.12, Jakarta Pusat',
    note: 'Jangan pedas ya kak',
    restaurant: { lat: -6.1754, lng: 106.8272, name: 'FlavorDash Kitchen Pusat' },
  },
  {
    id: 'ORD-20240625-002',
    date: '2024-06-25',
    status: 'delivered',
    statusLabel: 'Terkirim',
    items: [
      { foodId: '3', name: 'Ayam Geprek Sambal', qty: 1, price: 28000 },
      { foodId: '5', name: 'Pisang Goreng Crispy', qty: 1, price: 12000 },
      { foodId: '7', name: 'Es Alpukat Krim', qty: 1, price: 18000 },
    ],
    deliveryFee: 7000,
    address: 'Jl. Kebon Sirih No.12, Jakarta Pusat',
    note: '',
    restaurant: { lat: -6.2088, lng: 106.8456, name: 'FlavorDash Cabang Selatan' },
  },
  {
    id: 'ORD-20240620-003',
    date: '2024-06-20',
    status: 'processing',
    statusLabel: 'Diproses',
    items: [
      { foodId: '8', name: 'Martabak Manis Spesial', qty: 1, price: 35000 },
    ],
    deliveryFee: 5000,
    address: 'Jl. Kebon Sirih No.12, Jakarta Pusat',
    note: 'Topping cokelat double',
    restaurant: { lat: -6.1945, lng: 106.7891, name: 'FlavorDash Cabang Barat' },
  },
];
